version: "3"
services:
  recommendation-dbserver:
    image: postgres:latest
    container_name: "postgres"
    environment:
      - POSTGRES_DB=recommendation
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
    volumes:
      - "./data/postgres:/var/lib/postgresql/data"
    ports:
      - 5432:5432
    networks:
      - application
networks:
  application:
