version: "3"
services:
  recommendation:
    image: recommendation:0.0.1
    ports:
      - 8080:8080
    environment:
      - DATABASE_URL=jdbc:postgresql://recommendation-dbserver:5432/recommendation
      - ADMIN_URL=http://admin:8081
    networks:
      - application
  admin:
    image: monitoring:0.0.1
    ports:
      - 8081:8081
    networks:
      - application
networks:
  application:
